language: c
script: asdf plugin test elixir . --asdf-plugin-gitref $TRAVIS_BRANCH elixir --version
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
